version: "3.8"

services:
  webo:
    container_name: "${APP_NAME}_web"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${LOCAL_SERVER_PORT}:80
    volumes:
      - ./public:/var/www/html
    working_dir: /var/www/html
    # environment:
    #   VIRTUAL_HOST: ${APP_NAME}.zeroyon-preview.com
    # networks:
    #   - default
    #   - nginx-proxy

# networks:
#   nginx-proxy:
#     external: true
#     name: nginx-proxy-network

